# Generated by Django 4.1.7 on 2023-03-25 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='want_work',
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_rating', models.PositiveSmallIntegerField(verbose_name='Общая оценка')),
                ('count_raiting', models.PositiveSmallIntegerField(verbose_name='Количество голосов')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='Оценка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
